### ISSUE TITLE
Application yaml issue

### ISSUE THREAD

**Issue by GrecPetroff** [Inspiri0n/into-task-vivat3-internship-2023#1]
```
server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/presentations-inspir0n
    username: postgres
    password:
  flyway:
      locations: classpath:db/migration
      baseline-on-migrate: true
```

Fixed placement of flyway. Should be on same level as datasource

Also remove passwords from yaml. Not secured 🗡️
